package com.example.kingsapp.manager

class NaisTabConstants {
    var TAB_STUDENT_INFORMATION = "24"
    var EMAIL_HELP="8"
    var TAB_CALENDAR = "1"
    var TAB_MESSAGES = "9"
    var TAB_COMMUNICATION = "4"
    var TAB_REPORT_ABSENCE = "15"
    var TAB_TEACHER_CONTACT = "2"
    var TAB_SOCIAL_MEDIA = "12"
    var TAB_REPORTS = "6"
    //    var TAB_ATTENDANCE = "9"
    var TAB_TIME_TABLE = "3"
    var TAB_FORMS = "10"
    var TAB_TERM_DATES = "9"
    var TAB_CURRICULUM = "12"
    var TAB_UPDATE = "13"
    var TAB_CONTACT_US = "7"
    var TAB_APPS = "5"

    var TAB_HOME = "16"
    var TAB_NOTIFICATIONS = "17"
    var TAB_PAYMENTS = "18"
    var TAB_LUNCHBOX = "19"
    var TAB_PARENTESSENTIALS = "20"
    var TAB_EARLY_YEARS = "21"
    var TAB_PRIMARY = "22"
    var TAB_SECONDARY = "23"
    var TAB_SIXTHFORM = "24"
    var TAB_UNIVERSITY_GUIDENCE = "25"
    var TAB_SPORTS = "26"
    var TAB_PERFORMING_ARTS = "27"
    var TAB_EAPS = "28"
    var TAB_NAE_PROGRAMMES = "29"


    var TAB_PERMISSION_FORMS = "30"
    var TAB_GALLERY = "31"
    var TAB_ABOUT_US = "32"
    var TAB_CONTACT_Us = "33"
}